CMK-449: Add Werk 5267
5276 FIX cmk-update-agent: Restore compatibility to older python versions (Regression since 1.4.0p25)

This werk fixes an issue that occurs when cmk-update-agent is executed with a Python version of 2.5 or earlier. It would crash with an error message like

<pre>
except IOError as exc:
               ^
SyntaxError: invalid syntax
</pre>

Change-Id: I4a12ebc6a961147892ebbfdec4244603bec91882